Installing bobtemplates.ploneâ€¦
Downloading/unpacking bobtemplates.plone
  Running setup.py (path:/home/ubuntu/.local/share/virtualenvs/src-n3yXyIrJ/build/bobtemplates.plone/setup.py) egg_info for package bobtemplates.plone
    
    warning: no previously-included files matching '*pyc' found anywhere in distribution
Requirement already satisfied (use --upgrade to upgrade): setuptools in /home/ubuntu/.local/share/virtualenvs/src-n3yXyIrJ/lib/python2.7/site-packages (from bobtemplates.plone)
Downloading/unpacking mr.bob (from bobtemplates.plone)
  Downloading mr.bob-0.1.2.tar.gz
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/src-n3yXyIrJ/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/ubuntu/.local/share/virtualenvs/src-n3yXyIrJ/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/ubuntu/.local/share/virtualenvs/src-n3yXyIrJ/local/lib/python2.7/site-packages/pip/req.py", line 1197, in prepare_files
    do_download,
  File "/home/ubuntu/.local/share/virtualenvs/src-n3yXyIrJ/local/lib/python2.7/site-packages/pip/req.py", line 1375, in unpack_url
    self.session,
  File "/home/ubuntu/.local/share/virtualenvs/src-n3yXyIrJ/local/lib/python2.7/site-packages/pip/download.py", line 582, in unpack_http_url
    unpack_file(temp_location, location, content_type, link)
  File "/home/ubuntu/.local/share/virtualenvs/src-n3yXyIrJ/local/lib/python2.7/site-packages/pip/util.py", line 625, in unpack_file
    untar_file(filename, location)
  File "/home/ubuntu/.local/share/virtualenvs/src-n3yXyIrJ/local/lib/python2.7/site-packages/pip/util.py", line 556, in untar_file
    path = os.path.join(location, fn)
  File "/home/ubuntu/.local/share/virtualenvs/src-n3yXyIrJ/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 31: ordinal not in range(128)

Storing debug log for failure in /home/ubuntu/.pip/pip.log

